import type {
  Company,
  Site,
  Camera,
  Alert,
  Incident,
  RolePermission,
} from './types'

// Legacy types kept for backward compat until mock-data is deleted
type Guard = any
type TeamMember = any
type LegacyReport = any
type LegacyActivityItem = any

export const COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Apex Retail Group',
    type: 'Retail',
    sites: 12,
    users: 34,
    status: 'Active',
  },
  {
    id: 'c2',
    name: 'Nexus Logistics',
    type: 'Logistics',
    sites: 7,
    users: 18,
    status: 'Active',
  },
  {
    id: 'c3',
    name: 'Orion Healthcare',
    type: 'Healthcare',
    sites: 4,
    users: 22,
    status: 'Pending',
  },
  {
    id: 'c4',
    name: 'Pinnacle Finance',
    type: 'Finance',
    sites: 3,
    users: 9,
    status: 'Suspended',
  },
]

export const SITES: Site[] = [
  {
    id: 's1',
    company_id: 'c1',
    name: 'Apex Retail — Westfield',
    type: 'Retail',
    address: '123 Westfield Blvd, Sydney NSW',
    risk: 'High',
    status: 'Active',
    cameras: 24,
  },
  {
    id: 's2',
    company_id: 'c1',
    name: 'Apex Retail — Bondi',
    type: 'Retail',
    address: '45 Campbell Pde, Bondi Beach NSW',
    risk: 'Medium',
    status: 'Active',
    cameras: 16,
  },
  {
    id: 's3',
    company_id: 'c2',
    name: 'Nexus Warehouse A',
    type: 'Warehouse',
    address: '9 Industrial Dr, Prestons NSW',
    risk: 'Medium',
    status: 'Active',
    cameras: 32,
  },
  {
    id: 's4',
    company_id: 'c2',
    name: 'Nexus Warehouse B',
    type: 'Warehouse',
    address: '14 Commerce Rd, Moorebank NSW',
    risk: 'Low',
    status: 'Maintenance',
    cameras: 28,
  },
  {
    id: 's5',
    company_id: 'c3',
    name: 'Orion Clinic — Parramatta',
    type: 'Healthcare',
    address: '78 Church St, Parramatta NSW',
    risk: 'Low',
    status: 'Active',
    cameras: 10,
  },
  {
    id: 's6',
    company_id: 'c4',
    name: 'Pinnacle HQ',
    type: 'Office',
    address: '1 Martin Pl, Sydney NSW',
    risk: 'High',
    status: 'Inactive',
    cameras: 18,
  },
]

export const CAMERAS: Camera[] = [
  {
    id: 'cam1',
    site_id: 's1',
    name: 'CAM-01',
    location: 'Main Entrance',
    status: 'Online',
    last_checked: '2025-06-14T08:00:00Z',
    warning: null,
  },
  {
    id: 'cam2',
    site_id: 's1',
    name: 'CAM-02',
    location: 'Car Park Level 1',
    status: 'Online',
    last_checked: '2025-06-14T08:00:00Z',
    warning: null,
  },
  {
    id: 'cam3',
    site_id: 's1',
    name: 'CAM-03',
    location: 'Loading Dock',
    status: 'Offline',
    last_checked: '2025-06-13T22:15:00Z',
    warning: 'No signal for 9 h',
  },
  {
    id: 'cam4',
    site_id: 's2',
    name: 'CAM-04',
    location: 'Storefront',
    status: 'Online',
    last_checked: '2025-06-14T07:55:00Z',
    warning: null,
  },
  {
    id: 'cam5',
    site_id: 's3',
    name: 'CAM-05',
    location: 'Receiving Bay',
    status: 'Maintenance',
    last_checked: '2025-06-12T10:00:00Z',
    warning: 'Scheduled lens replacement',
  },
  {
    id: 'cam6',
    site_id: 's3',
    name: 'CAM-06',
    location: 'Racking Aisle 3',
    status: 'Online',
    last_checked: '2025-06-14T08:01:00Z',
    warning: null,
  },
  {
    id: 'cam7',
    site_id: 's5',
    name: 'CAM-07',
    location: 'Reception',
    status: 'Online',
    last_checked: '2025-06-14T08:00:00Z',
    warning: null,
  },
  {
    id: 'cam8',
    site_id: 's6',
    name: 'CAM-08',
    location: 'Server Room',
    status: 'Unknown',
    last_checked: '2025-06-10T14:30:00Z',
    warning: 'Site inactive — feed unavailable',
  },
]

export const GUARDS: Guard[] = [
  {
    id: 'g1',
    name: 'Marcus Webb',
    status: 'On Incident',
    zone: 'Westfield — Car Park',
    phone: '0412 111 222',
    shifts: 'Mon–Fri 18:00–06:00',
  },
  {
    id: 'g2',
    name: 'Priya Nair',
    status: 'Available',
    zone: 'Nexus Warehouse A',
    phone: '0412 333 444',
    shifts: 'Mon–Sat 06:00–18:00',
  },
  {
    id: 'g3',
    name: 'Damien Frost',
    status: 'Available',
    zone: 'Bondi Retail',
    phone: '0412 555 666',
    shifts: 'Wed–Sun 12:00–24:00',
  },
  {
    id: 'g4',
    name: 'Leila Santos',
    status: 'Off-duty',
    zone: 'Orion Clinic',
    phone: '0412 777 888',
    shifts: 'Mon–Fri 08:00–20:00',
  },
]

export const ALERTS: Alert[] = [
  {
    id: 'a1',
    title: 'Perimeter breach detected',
    site_id: 's1',
    camera_id: 'cam3',
    severity: 'Critical',
    status: 'New',
    created_at: '2025-06-14T02:17:00Z',
    description: 'Motion detected at Loading Dock outside business hours. Camera feed lost immediately after.',
    source: 'AI Motion Detection',
  },
  {
    id: 'a2',
    title: 'Unattended bag — Main Entrance',
    site_id: 's1',
    camera_id: 'cam1',
    severity: 'Warning',
    status: 'Reviewing',
    created_at: '2025-06-14T07:45:00Z',
    description: 'Object left unattended for >5 minutes near turnstiles.',
    source: 'AI Object Detection',
  },
  {
    id: 'a3',
    title: 'After-hours access — Receiving Bay',
    site_id: 's3',
    camera_id: 'cam5',
    severity: 'Warning',
    status: 'Escalated',
    created_at: '2025-06-13T23:50:00Z',
    description: 'Door access card used outside permitted hours.',
    source: 'Access Control',
  },
  {
    id: 'a4',
    title: 'Camera offline',
    site_id: 's1',
    camera_id: 'cam3',
    severity: 'Info',
    status: 'Reviewing',
    created_at: '2025-06-13T22:15:00Z',
    description: 'CAM-03 at Loading Dock has lost network connectivity.',
    source: 'System Monitor',
  },
  {
    id: 'a5',
    title: 'Crowd density threshold exceeded',
    site_id: 's2',
    camera_id: 'cam4',
    severity: 'Warning',
    status: 'Closed',
    created_at: '2025-06-14T12:30:00Z',
    description: 'Occupancy exceeded 95% capacity at Bondi storefront.',
    source: 'AI Analytics',
  },
  {
    id: 'a6',
    title: 'Fire panel fault',
    site_id: 's5',
    camera_id: null,
    severity: 'Critical',
    status: 'New',
    created_at: '2025-06-14T06:05:00Z',
    description: 'Zone 3 fire panel is reporting a fault condition.',
    source: 'Building Management System',
  },
]

export const INCIDENTS: Incident[] = [
  {
    id: 'i1',
    title: 'Loading Dock perimeter breach',
    site_id: 's1',
    alert_id: 'a1',
    severity: 'Critical',
    status: 'Dispatched',
    guard_id: 'g1',
    started_at: '2025-06-14T02:20:00Z',
    notes: 'Guard Marcus Webb dispatched to Loading Dock. Awaiting on-site confirmation.',
  },
  {
    id: 'i2',
    title: 'Unattended bag investigation',
    site_id: 's1',
    alert_id: 'a2',
    severity: 'Warning',
    status: 'In Progress',
    guard_id: 'g1',
    started_at: '2025-06-14T07:48:00Z',
    notes: 'Guard on scene. Bag identified as belonging to cleaning staff.',
  },
  {
    id: 'i3',
    title: 'Receiving Bay after-hours access',
    site_id: 's3',
    alert_id: 'a3',
    severity: 'Warning',
    status: 'Open',
    guard_id: null,
    started_at: '2025-06-13T23:55:00Z',
    notes: 'Access log pulled. Reviewing card holder identity.',
  },
  {
    id: 'i4',
    title: 'Orion Clinic fire panel fault',
    site_id: 's5',
    alert_id: 'a6',
    severity: 'Critical',
    status: 'Open',
    guard_id: null,
    started_at: '2025-06-14T06:10:00Z',
    notes: 'Maintenance contractor notified. Fire brigade on standby.',
  },
  {
    id: 'i5',
    title: 'Bondi crowd density event',
    site_id: 's2',
    alert_id: 'a5',
    severity: 'Warning',
    status: 'Resolved',
    guard_id: 'g3',
    started_at: '2025-06-14T12:32:00Z',
    notes: 'Entry queue managed. Density returned to normal within 20 min.',
  },
]

export const REPORTS: LegacyReport[] = [
  {
    id: 'r1',
    name: 'June 2025 — Apex Retail Monthly',
    company: 'Apex Retail Group',
    date: '2025-06-01',
    type: 'Monthly',
    incidents: 14,
    size: '1.2 MB',
  },
  {
    id: 'r2',
    name: 'May 2025 — Nexus Logistics Monthly',
    company: 'Nexus Logistics',
    date: '2025-05-01',
    type: 'Monthly',
    incidents: 6,
    size: '890 KB',
  },
  {
    id: 'r3',
    name: 'Q1 2025 — Apex Retail Quarterly',
    company: 'Apex Retail Group',
    date: '2025-03-31',
    type: 'Quarterly',
    incidents: 38,
    size: '3.4 MB',
  },
  {
    id: 'r4',
    name: 'Westfield Incident — 2025-06-14',
    company: 'Apex Retail Group',
    date: '2025-06-14',
    type: 'Incident',
    incidents: 2,
    size: '420 KB',
  },
  {
    id: 'r5',
    name: 'Orion Healthcare Onboarding Audit',
    company: 'Orion Healthcare',
    date: '2025-06-10',
    type: 'Audit',
    incidents: 0,
    size: '210 KB',
  },
]

export const TEAM: TeamMember[] = [
  {
    name: 'Jordan Blake',
    role: 'super_admin',
    email: 'jordan@primexsecurity.com.au',
    last_active: '2025-06-14T08:05:00Z',
    status: 'Active',
  },
  {
    name: 'Samira Osei',
    role: 'dispatcher',
    email: 'samira@primexsecurity.com.au',
    last_active: '2025-06-14T07:58:00Z',
    status: 'Active',
  },
  {
    name: 'Tom Nguyen',
    role: 'dispatcher',
    email: 'tom@primexsecurity.com.au',
    last_active: '2025-06-13T23:10:00Z',
    status: 'Active',
  },
  {
    name: 'Claire Mackay',
    role: 'company_manager',
    email: 'claire@apexretail.com.au',
    last_active: '2025-06-14T06:30:00Z',
    status: 'Active',
  },
  {
    name: 'Marcus Webb',
    role: 'guard',
    email: 'marcus@primexsecurity.com.au',
    last_active: '2025-06-14T02:22:00Z',
    status: 'Active',
  },
  {
    name: 'Priya Nair',
    role: 'guard',
    email: 'priya@primexsecurity.com.au',
    last_active: '2025-06-14T07:50:00Z',
    status: 'Active',
  },
  {
    name: 'Brett Collins',
    role: 'client',
    email: 'brett@nexuslogistics.com.au',
    last_active: '2025-06-10T11:00:00Z',
    status: 'Inactive',
  },
]

export const ROLES_PERMS: RolePermission[] = [
  {
    role: 'Super Admin',
    count: 2,
    perms: 'Full system access — all companies, sites, users, billing',
  },
  {
    role: 'Company Manager',
    count: 4,
    perms: 'Manage own company sites, users, view reports',
  },
  {
    role: 'Dispatcher',
    count: 3,
    perms: 'View alerts/incidents, dispatch guards, update incident status',
  },
  {
    role: 'Guard',
    count: 8,
    perms: 'View assigned incidents, update status, submit patrol logs',
  },
  {
    role: 'Client',
    count: 12,
    perms: 'View own site cameras, alerts summary, download reports',
  },
]

export const ACTIVITY: LegacyActivityItem[] = [
  {
    who: 'System',
    what: 'Critical alert raised',
    target: 'Loading Dock — Westfield',
    when: '2025-06-14T02:17:00Z',
    icon: 'Bell',
    tone: 'red',
  },
  {
    who: 'Samira Osei',
    what: 'Dispatched guard',
    target: 'Marcus Webb → Westfield',
    when: '2025-06-14T02:20:00Z',
    icon: 'Radio',
    tone: 'amber',
  },
  {
    who: 'System',
    what: 'Camera went offline',
    target: 'CAM-03 — Loading Dock',
    when: '2025-06-13T22:15:00Z',
    icon: 'WifiOff',
    tone: 'red',
  },
  {
    who: 'Tom Nguyen',
    what: 'Incident status updated',
    target: 'Receiving Bay after-hours → Open',
    when: '2025-06-13T23:58:00Z',
    icon: 'ClipboardList',
    tone: 'amber',
  },
  {
    who: 'System',
    what: 'Fire panel fault detected',
    target: 'Orion Clinic — Zone 3',
    when: '2025-06-14T06:05:00Z',
    icon: 'Bell',
    tone: 'red',
  },
  {
    who: 'Damien Frost',
    what: 'Incident resolved',
    target: 'Bondi crowd density event',
    when: '2025-06-14T12:52:00Z',
    icon: 'CheckCircle',
    tone: 'green',
  },
  {
    who: 'Jordan Blake',
    what: 'New company added',
    target: 'Orion Healthcare',
    when: '2025-06-10T09:00:00Z',
    icon: 'Building2',
    tone: 'blue',
  },
  {
    who: 'Claire Mackay',
    what: 'Report downloaded',
    target: 'June 2025 — Apex Retail Monthly',
    when: '2025-06-14T08:10:00Z',
    icon: 'FileDown',
    tone: 'gray',
  },
  {
    who: 'Jordan Blake',
    what: 'User account created',
    target: 'brett@nexuslogistics.com.au',
    when: '2025-06-09T14:20:00Z',
    icon: 'UserPlus',
    tone: 'blue',
  },
  {
    who: 'System',
    what: 'Site status changed',
    target: 'Pinnacle HQ → Inactive',
    when: '2025-06-08T11:00:00Z',
    icon: 'MapPin',
    tone: 'gray',
  },
]
